services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${PG_DATABASE}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_USER=${PG_USER}'
    ports:
      - '${PG_PORT}'
